### ISSUE TITLE
Small typo in wrapper scripts

### ISSUE THREAD

**Issue by leannmlindsey** [kuleshov-group/caduceus#12]
Thank you for providing such complete reproducibility instructions and code.

I found a small typo when trying to duplicate your results.

In the wrapper_run_genomics.sh script, the CONFIG_PATH and PRETRAINED_PATHS are looking for a directory of the form 

"caduceus-ps...."

But the run_pretrain_caduceus.sh seems to create directories of a slightly different form

"caduceus_ps..."

#CONFIG_PATH=$(realpath "../outputs/pretrain/hg38/caduceus-ps_seqlen-1k_d_model-118_n_layer-4_lr-8e-3/model_config.json")
#PRETRAINED_PATH=$(realpath "../outputs/pretrain/hg38/caduceus-ps_seqlen-1k_d_model-118_n_layer-4_lr-8e-3/checkpoints/last.ckpt")

**Comment by yair-schiff** [comment]
Thank you for pointing this out. I'll push a fix
