### ISSUE TITLE
How to load pre-trained model for fine-tuning?

### ISSUE THREAD

**Issue by zhan8855** [kuleshov-group/caduceus#14]
Hi, thank you for your awesome work!

However, I am facing difficulties to load huggingface checkpoints for further fine-tuning using the slurm scripts. It seems that the huggingface configs cannot align with the slurm model configs. I am trying to fix this by adding "_target_": "caduceus.configuration_caduceus.CaduceusConfig" to the huggingface configs. Is it okay?

What's more, I still have no idea on how to load the model. Could you please offer me some suggestions? Or could you please release the pre-trained checkpoints produced by slurm scripts? Thank you very much in advance!

**Comment by zhan8855** [comment]
The tilt target above should be  "__ target __"

**Comment by leannmlindsey** [comment]
I second releasing the pre-trained checkpoints.  It is not too much work to pre-train, but you do have to have 8 A100 and or 8 A6000 GPUs which is sometimes hard to access.

Also, I felt like I couldn't use my checkpoints on my downstream task until I had reproduced all of your results to verify that I had the correct model. It is a lot of extra work for researchers who just want to make use of this wonderful resource.

**Comment by yair-schiff** [comment]
> However, I am facing difficulties to load huggingface checkpoints for further fine-tuning using the slurm scripts. It seems that the huggingface configs cannot align with the slurm model configs. I am trying to fix this by adding "target": "caduceus.configuration_caduceus.CaduceusConfig" to the huggingface configs. Is it okay?

Yes currently the code is not compatible with HF models, but I created a branch here: https://github.com/kuleshov-group/caduceus/tree/hf_finetune where you can now load HF Caducueus models for downstream tasks, e.g., Genmoics Benchmark and Nucleotide Transformer. See these wrapper scripts for how to use them:
- https://github.com/kuleshov-group/caduceus/blob/hf_finetune/slurm_scripts/wrapper_run_nucleotide_transformer_hf.sh
- https://github.com/kuleshov-group/caduceus/blob/hf_finetune/slurm_scripts/wrapper_run_genomics_hf.sh

Please let me know if you still have questions

**Comment by yair-schiff** [comment]
> I second releasing the pre-trained checkpoints. It is not too much work to pre-train, but you do have to have 8 A100 and or 8 A6000 GPUs which is sometimes hard to access.
> 
> Also, I felt like I couldn't use my checkpoints on my downstream task until I had reproduced all of your results to verify that I had the correct model. It is a lot of extra work for researchers who just want to make use of this wonderful resource.

I pushed the models for the Genomics Benchmark and Nucleotide Transformer to the HF Hub. You can use them as described in the [comment above](https://github.com/kuleshov-group/caduceus/issues/14#issuecomment-2059942518)
**Genomics Benchmark**
- https://huggingface.co/kuleshov-group/caduceus-ph_seqlen-1k_d_model-118_n_layer-4_lr-8e-3
- https://huggingface.co/kuleshov-group/caduceus-ps_seqlen-1k_d_model-118_n_layer-4_lr-8e-3

**Nucleotide Transformer**
- https://huggingface.co/kuleshov-group/caduceus-ph_seqlen-1k_d_model-256_n_layer-4_lr-8e-3
- https://huggingface.co/kuleshov-group/caduceus-ps_seqlen-1k_d_model-256_n_layer-4_lr-8e-3

**Comment by zhan8855** [comment]
Thank you so much!!

**Comment by leannmlindsey** [comment]
Thank you Yair!
