### ISSUE TITLE
Inconsistency between pre-training slurm scripts and the training details in the paper

### ISSUE THREAD

**Issue by zhan8855** [kuleshov-group/caduceus#15]
Hi, thank you for your awesome work!

However, it is a little difficult for me to reproduce the pre-training experiments, since I found the slurm scripts in the repo did not align with the hyperparameters discussed in the paper. For example, in run_pretrain_caduceus.sh, the context length is set to 131K while the N_LAYER is set to 8, which does not agree with Table 3 in the paper. Could you please release the slurm scripts which exactly reproduce the pre-training of Caduceus-Ph and Caduceus-Ps?

What's more, in run_pretrain_hyena.sh and run_pretrain_mamba.sh, I found their MAX_STEPS are less than 50000, which cannot be used as baselines to compare fairly with Caduceus. Could you please release the slurm scripts which exactly reproduce these two baselines as well?

 Thank you very much in advance.

**Comment by yair-schiff** [comment]
All of the pre-training hyperparameters are detailed in the Appendix of the [paper](https://arxiv.org/abs/2403.03234)

You need to update these parameters accordingly:
```
SEQLEN=
MAX_STEPS=
D_MODEL=
N_LAYER=
```

For **Genomics Benchmark** here are the values you need:
| Model | `SEQLEN` | `MAX_STEPS` | `D_MODEL` | N_LAYER` |
|---|---|---|---|---|
| Hyena | 1k | 10k | 128 | 2 |
| Mamba | 1k | 10k | 128 | 4 |
| Caduceus | 1k | 10k | 118 | 4|

For **Nucleotide Transformer tasks** here are the values you need:
| Model | `SEQLEN` | `MAX_STEPS` | `D_MODEL` | N_LAYER` |
|---|---|---|---|---|
| Hyena | 1k | 10k | 256 | 2 |
| Mamba | 1k | 10k | 256 | 4 |
| Caduceus | 1k | 10k | 256 | 4|

**Comment by zhan8855** [comment]
Thank you so much!!
