### ISSUE TITLE
The size of the vocab is inconsistent with the output dimension of the lm_head

### ISSUE THREAD

**Issue by jaminzzz** [kuleshov-group/caduceus#17]
Hello,  awesome work！

I'm confused as to why the vocabulary size (12) and the output dimension of lm head (16) are inconsistent?

Looking forward to your reply！
<img width="1119" alt="2024-04-12 22 42 12" src="https://github.com/kuleshov-group/caduceus/assets/62273762/13bc32d1-a88f-4f64-a666-1790c8553fca">

**Comment by yair-schiff** [comment]
This is because the Mamba/Caduceus config has a parameter named `pad_vocab_size_multiple`, which pads the vocab to a multiple of some number. We set this value to 8, hence the model embeddding / LM head output get expanded from 12 to 16.
