### ISSUE TITLE
Slurm scripts for downstream tasks

### ISSUE THREAD

**Issue by zhan8855** [kuleshov-group/caduceus#18]
Hi, thank you for your awesome work!

Could you please release the exact script to reproduce downstream results? i.e. Could you please fill out this part in run_genomics_benchmark.sh and run_nucleotide_transformer.sh, for both Caduceus-Ph and Caduceus-Ps?

Expected args:
- CONFIG_PATH
- PRETRAINED_PATH
- DISPLAY_NAME
- MODEL
- MODEL_NAME
- CONJOIN_TRAIN_DECODER
- CONJOIN_TEST
- TASK
- LR
- BATCH_SIZE
- RC_AUG

Thank you very much in advance!

**Comment by yair-schiff** [comment]
The exact values of these parameters are set in the `wrapper_` scripts for each of the downstream tasks:
- https://github.com/kuleshov-group/caduceus/blob/main/slurm_scripts/wrapper_run_genomics.sh
- https://github.com/kuleshov-group/caduceus/blob/main/slurm_scripts/wrapper_run_nucleotide_transformer.sh

The appendix in the [paper](https://arxiv.org/abs/2403.03234) has additional details about hyperparameters such as `BATCH_SIZE` and `LR` for each subtask within a benchmark

**Comment by zhan8855** [comment]
Thank you so much!!
