### ISSUE TITLE
LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.shfl.sync.bfly.i32

### ISSUE THREAD

**Issue by Jellymoon** [kuleshov-group/caduceus#2]
Hello,

I was trying to follow the instructions from "Getting started in this repository" to "Pretraining on Human Reference Genome" and I ran into a couple of issues:
1.  There is a '=' missing in the caduceus_env.yml line 32 for 'pytest=8.0.2'
2.  When following the instructions for creating the environment I ran into the issue that causal-conv1d and mamba-ssm could not be installed because torch was missing. So I created an empty environment, commented both out, updated the environment with the 'caduceus_env.yml', commented them back in and updated the environment again. This fixed the installation issues.
3.  After following the next few instructions I run into the following error when running the "Pretraining on Human Reference Genome":
        ```Sanity Checking DataLoader 0:   0%|```
        ```LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.shfl.sync.bfly.i32```
        ```Aborted```

I am using Ubuntu on WSL2. Also maybe my 'fix' for issue 2. lead to issue 3. but I am not sure and I also don't know how to fix it otherwise.  Any ideas for the LLVM error?

**Comment by yair-schiff** [comment]
> There is a '=' missing in the caduceus_env.yml line 32 for 'pytest=8.0.2'

Thanks! I'll update the env file.

For the issue you're hitting. Can you try the following potential solutions:
- Move `causal-conv` and `mamba-ssm` to later in the pip dependencies list in `caduceus_env.yaml` (the ordering here might be enforced at install)
- Try removing `causal-conv` and `mamba-ssm` from the env file altogether. Create the environemt using the edited env file and then activate it and pip install these packages:
```
conda env create -f caduceus_env.yml  # the edited one with the packages above removed
conda activate caduceus_env
pip install flash-attn==2.5.5 --no-build-isolation
pip install causal-conv1d==1.1.3.post1
pip install mamba-ssm==1.1.4
```

Please let me know if this helps resolve your issue!

**Comment by yair-schiff** [comment]
Ok. Thanks for trying that. I’ll look into this on my
end as well and report back soon. 

On the bright side, I think the fact that we’re debugging a conda env means we’re doing real DL research 😅

**Comment by yair-schiff** [comment]
@Jellymoon , I believe this issue is related to this [issue](https://github.com/state-spaces/mamba/issues/173), which I believe is being caused by the GPU architecture not being compatible with the code in that package. What GPU are you using?

**Comment by yair-schiff** [comment]
When I install the env from scratch with the updated yaml on a newer machine (e.g. A6000), I don't hit this error.

**Comment by ACatFromPoland** [comment]
Yes the GTX 1070 is built on the Pascal architecture which does not support the intrinsics necessary for this project.
I had the same issue with my GTX 1080 ti which is built on the same architecture.

**Comment by Airbornharsh** [comment]
I the issue solved
i ma facing the same error can anyone help

**Comment by yair-schiff** [comment]
I don't believe there is a "resolution" to this issue. Certain GPU architectures will simply not be compatible with the mamba code.
