### ISSUE TITLE
pretraining parameters for caduceus-ph and caduceus w/o equivariance

### ISSUE THREAD

**Issue by leannmlindsey** [kuleshov-group/caduceus#21]
I am trying to pre-train the models used in your genomic benchmark results and I was wondering if you could tell me how to modify these parameters to obatin the cacudeus-ph model and the caduceus w/o equivariance model.

This is a section of the code from run_pretrain_caduceus.sh

SEQLEN=1024
MAX_STEPS=50000
D_MODEL=256
N_LAYER=4
LR="8e-3"
BIDIRECTIONAL_STRATEGY="add"
BIDIRECTIONAL_WEIGHT_TIE="true"
RCPS="true"
RC_AUG="false"

Looking through the code I found that the options for each are:

BIDIRECTIONAL_STRATEGY={"add","ew_multiply"}
BIDRECTIONAL_WEIGHT_TIE={"false","true"}
RCPS={"false","true"}
RC_AUG={"false","true"}

**Comment by yair-schiff** [comment]
Pre-training Caduceus-Ph and Caduceus w/o Equivariance for the Genomics Benchmark task will be the same. use the following parameters:
```
SEQLEN=1024
MAX_STEPS=10000
D_MODEL=118
N_LAYER=4
LR="8e-3"
BIDIRECTIONAL_STRATEGY="add"
BIDIRECTIONAL_WEIGHT_TIE="true"
RCPS="false"
RC_AUG="true"
```

The difference between these models is how they are used at downstream time. For example, Caduceus w/o Equiv would be used as [here](https://github.com/kuleshov-group/caduceus/blob/17452f8c4066f5d562fdcfb3e4f28534cdc31015/slurm_scripts/wrapper_run_genomics.sh#L30-L40)
and Caduceus-Ph would be used as [here](https://github.com/kuleshov-group/caduceus/blob/17452f8c4066f5d562fdcfb3e4f28534cdc31015/slurm_scripts/wrapper_run_genomics.sh#L42-L52).

**Comment by leannmlindsey** [comment]
Thank you so much.
