### ISSUE TITLE
High Storage Requirements for Running vep_embeddings.py in EQTL VEP Analysis

### ISSUE THREAD

**Issue by yangzhao1230** [kuleshov-group/caduceus#28]
Hi,

Thanks for your great work and well-documented code.

 I'm currently facing an issue related to the storage requirements for running the vep_embeddings.py script as part of the EQTL VEP analysis. It seems that the script requires an unexpectedly high amount of storage space.

To date, running this script has already consumed over 800GB of local storage, and it continues to require more. This level of storage demand is quite substantial and seems unusual for typical usage. I would like to understand if this is expected behavior or if there might be a potential issue with how the script handles data.

**Comment by yair-schiff** [comment]
This definitely sounds like a memory leak of some sort, unfortunately. I did not observe such high memory usage

**Comment by yangzhao1230** [comment]
<img width="676" alt="image" src="https://github.com/kuleshov-group/caduceus/assets/52462696/b4190e0c-4996-4550-95a6-f596e3485f81">

Today, I restarted using a machine with 8 GPUs to run the vep_embeddings.py script from your Caduceus project. I set the environment variable HF_HOME in a newly created directory under the project directory named huggingface, meaning that all memory generated is solely from this script. The memory generated and the configuration I used can be seen in my figure. Additionally, this script has been running for almost a day now and it still hasn't finished processing. I would like to know if such high memory and time requirements are normal. Thank you. My configuration is exactly based on the Enformer setup you provided, with the same number of GPUs; the only change I made was to increase the number of workers.

**Comment by yangzhao1230** [comment]
The figure shows Enformer, but I've experienced similar high memory and time requirements using Caduceus as well. Currently, I have not yet finished the step of preparing the dataset.

**Comment by yair-schiff** [comment]
What sequence length are you downloading for this dataset? On disk size for 131k for me is about `350G`

**Comment by yangzhao1230** [comment]
> What sequence length are you downloading for this dataset? On disk size for 131k for me is about `350G`

The same as you. Thanks!

**Comment by yangzhao1230** [comment]
The reason for the previous high storage usage was due to many cache files. By the way, I want to ask about this task. In the paper, are the results obtained by taking the longest theoretical length of each model for embedding, then using the center 1536bp to train the SVM?

**Comment by yair-schiff** [comment]
The length is model-specific, yes. Please see here for what we use for each model: https://github.com/kuleshov-group/caduceus/blob/hf_finetune/slurm_scripts/dump_vep_embeddings.sh

Yes, we take the center 1536bp, but please note that this will translate to a different number of **tokens** depending on the model. For example, for Caduceus since we use bp tokenization, this will also correspond to 1536 tokens, but for Nucleotide Transformer, which uses 6-mer tokenization, this will correspond to 1536/ 6 = 256 tokens.

**Comment by yangzhao1230** [comment]
<img width="717" alt="image" src="https://github.com/kuleshov-group/caduceus/assets/52462696/bad50ae0-ac1b-450b-ad82-c63099264fbf">
Why does Caduceus-PS use an input length of 16k?

**Comment by yangzhao1230** [comment]
<img width="717" alt="image" src="https://github.com/kuleshov-group/caduceus/assets/52462696/bad50ae0-ac1b-450b-ad82-c63099264fbf">
@yair-schiff Thanks for your help. But I'd like to know why Caduceus-PS uses an input length of 16k?

**Comment by yair-schiff** [comment]
That is a typo. Thanks for catching that! I'll push a correction later today

**Comment by yair-schiff** [comment]
@yangzhao1230 , this should be fixed now.
