### ISSUE TITLE
Does Caduceus Support Variable-Length Inputs in Batches?

### ISSUE THREAD

**Issue by yangzhao1230** [kuleshov-group/caduceus#39]
I would like to inquire whether Caduceus supports variable-length inputs within a batch. From my understanding, the original MambaBlock does not support variable-length inputs, and it seems that Caduceus continues this limitation.

For downstream tasks, such as the NT benchmark where each task sequence has different lengths, I want to confirm whether Caduceus simply models the pad tokens added by the tokenizer along with the sequences.

**Comment by yair-schiff** [comment]
That is correct, variable length inputs in a batch would not work to the best of my understanding. You'd need to either truncate to shortest or pad to longest sequence in the batch.
