### ISSUE TITLE
error when using hf model in genomic_benchmark pretrain

### ISSUE THREAD

**Issue by lyksj200** [kuleshov-group/caduceus#40]
It seems that I can use the model provided in the hugging face such as kuleshov-group/caduceus-ph_seqlen-1k_d_model-118_n_layer-4_lr-8e-3 and code in caduceus-hf_finetune to fine-tune model on the genomic_benchmark task.
I download model and then use cmd:
python -m train     experiment=hg38/genomic_benchmark     callbacks.model_checkpoint_every_n_steps.every_n_train_steps=5000     dataset.dataset_name="dummy_mouse_enhancers_ensembl"     dataset.train_val_split_seed=1     dataset.batch_size=128     dataset.rc_aug=false     +dataset.conjoin_train=false     +dataset.conjoin_test=false     loader.num_workers=2     model=caduceus     model._name_=dna_embedding_caduceus     +model.config_path=/cpfs01/projects-HDD/cfff-282dafecea22_HDD/liuxuyang/projects/gene/caduceus-hf_finetune/kuleshov-group/caduceus-ps_seqlen-1k_d_model-118_n_layer-4_lr-8e-3/config.json     +model.conjoin_test=false     +decoder.conjoin_train=true     +decoder.conjoin_test=false     optimizer.lr="1e-3"     trainer.max_epochs=10     train.pretrained_model_path=/cpfs01/projects-HDD/cfff-282dafecea22_HDD/liuxuyang/projects/gene/caduceus-hf_finetune/kuleshov-group/caduceus-ps_seqlen-1k_d_model-118_n_layer-4_lr-8e-3/model.safetensors     wandb=null
but it seems I didn't get the right config
![image](https://github.com/kuleshov-group/caduceus/assets/29789350/3a516181-0597-4e20-b67e-f5221d8c2e95)

**Comment by yair-schiff** [comment]
This parameter `model.config_path` refers to a model config that would have been generated if you ran the pre-training as well. To use an HF model for this downstream task please use this branch: [`hf_finetune`](https://github.com/kuleshov-group/caduceus/tree/hf_finetune) and see the discussion [here](https://github.com/kuleshov-group/caduceus/issues/14#issuecomment-2059942518)

**Comment by lyksj200** [comment]
Thank you for your answering. But I still can't use HF model using hf_finetune, my command is:
python -m train     experiment=hg38/genomic_benchmark     callbacks.model_checkpoint_every_n_steps.every_n_train_steps=5000     dataset.dataset_name="dummy_mouse_enhancers_ensembl"     dataset.train_val_split_seed=1     dataset.batch_size=128     dataset.rc_aug=false     +dataset.conjoin_train=false     +dataset.conjoin_test=false     loader.num_workers=2     model=caduceus     model._name_=dna_embedding_caduceus       +model.conjoin_test=false     +decoder.conjoin_train=true     +decoder.conjoin_test=false     optimizer.lr="1e-3"     trainer.max_epochs=10     train.pretrained_model_path=/cpfs01/projects-HDD/cfff-282dafecea22_HDD/liuxuyang/projects/gene/caduceus-hf_finetune/kuleshov-group/caduceus-ps_seqlen-1k_d_model-118_n_layer-4_lr-8e-3/model.safetensors wandb=null

and the error is 
![image](https://github.com/kuleshov-group/caduceus/assets/29789350/03e199a8-142e-44d8-99e6-63b3e3cb67ae)

**Comment by yair-schiff** [comment]
I believe you are still using the command / params for loading a model you pre-trained locally. Please instead refer to the commands/args defined in these files:
- https://github.com/kuleshov-group/caduceus/blob/hf_finetune/slurm_scripts/wrapper_run_genomics_hf.sh
- https://github.com/kuleshov-group/caduceus/blob/hf_finetune/slurm_scripts/run_genomics_benchmark_hf.sh

Namely, you will need to use `model.pretrained_model_name_or_path="${PRETRAINED_PATH}"` instead of `train.pretrained_model_path`, where `PRETRAINED_PATH` refers to either a HF path on the hub or locally

**Comment by lyksj200** [comment]
Thank you for your excellent work and outstanding answers.
