### ISSUE TITLE
The TF binding or enhancer activation is orientation independent

### ISSUE THREAD

**Issue by freedom-cognit** [kuleshov-group/caduceus#41]
In biology, the TF to TSS binding or the enhancer activation is orientation agnostic and does not affect the efficiency. Only the promoter efficiency can vary slightly in really complex regulations but are actually stabilized by proteins like CTCF or cohesion.

I am curious why the RC-equivariant is needed? It is obvious from the Human-Regulatory benchmark that there was no performance improvement from a uni-directional CNN and the PS and PH of Caduceus. 

I notice a significant jump on human-enhancer-ensembl and can't stop wondering if this has something to do with better feature extraction due to bi-directional feature-maps and nothing to do with biology? Was there a CNN comparison possible with bi-directional channels (feature maps)?

Thoughts?

**Comment by yair-schiff** [comment]
Let me clarify that Caduceus-Ph also takes into RC but only at downstream inference. That is this model is pre-trained and fine-tuned using RC **data augmentation**. Then at downstream **inference** the model is run **twice**: once on a sequence and once on its RC. The outputs from these two applications are averaged.

As for this question:
>Was there a CNN comparison possible with bi-directional channels (feature maps)?

I am not sure I fully understand what you are asking. Do you mind clarifying what you meant here?

**Comment by freedom-cognit** [comment]
Yes I understand that PH takes RC at downstream inference. I was commenting on seeing a comparison with a CNN model (Section 5.2.1, Table 1 in arxiv published document) that also aggregates on the RC. This can be done in several ways.

Few architectural takes:
- Incorporate bidirectional convolutional layers that process the input sequence in both forward and reverse directions, similar to bidirectional RNNs.
- Design a two-channel input where one channel represents the forward sequence and the other channel represents the reverse sequence. (expensive and not necessary)
- After applying convolutional filters, use pooling layers that aggregate features from both directions. This can be done by concatenating the outputs from the forward and reverse sequences and then applying a pooling operation. (similar to averaging in your PH case, but concats pooling layer outputs and one more round of pooling on the concatenation).

Curious to see if human-enhancer-ensembl score for a bi-directional CNN be closer to the PH model.
