### ISSUE TITLE
About pretrain GPUS

### ISSUE THREAD

**Issue by wyhsleep** [kuleshov-group/caduceus#42]
Dear authors, thank you for your wonderful work, may I ask how many GPUs (A100) you used for pretraining?

**Comment by Skylion007** [comment]
Max we ever used 8, most experiments were done on A6000 or other consumer experiments.

**Comment by lucaskbobadilla** [comment]
Similar question: How long it took to pre-train the model using the 8 A100?

**Comment by yair-schiff** [comment]
Roughly 7-8 hours
