### ISSUE TITLE
MCC calculations

### ISSUE THREAD

**Issue by leannmlindsey** [kuleshov-group/caduceus#48]
Yair,

Do you think that you will post an update to correct how the MCC is calculated on the test set?  (see my comments in this issue: https://github.com/kuleshov-group/caduceus/issues/38)

it would be so helpful.

Thank you
LeAnn

**Comment by leannmlindsey** [comment]
It would also be so useful to have all of the performance metrics instead of just one (ie accuracy MCC, f1 precision, recall)

**Comment by yair-schiff** [comment]
I don't think we planned on updating the dataloader there, but it seemed like in #38  that you had resolved the issue. Do you want to open a PR here with you fix?

**Comment by leannmlindsey** [comment]
I don't think it is necessary, as long as you shuffle the test files then the problem does not occur. It is only a problem in the Genomic Benchmark fine tuning because their test files are not shuffled.
