### ISSUE TITLE
ImportError with newer mamba_ssm

### ISSUE THREAD

**Issue by davidaknowles** [kuleshov-group/caduceus#51]
Hi - nice work on this. My current install of mamba_ssm is v2.2.2, which cadaceus doesn't like: 
```
from mamba_ssm.modules.mamba_simple import Mamba, Block
ImportError: cannot import name 'Block' from 'mamba_ssm.modules.mamba_simple' (/home/david/venvs/svg/lib/python3.10/site-packages/mamba_ssm/modules/mamba_simple.py)
```
I tried downgrading mamba but then it doesn't like my current CUDA (12.6) and I'd rather avoid having to downgrade that as well!

**Comment by gauthamp123** [comment]
Hi, I am having an issue with this as well. What version do I have to downgrade to gain access to the Block module? Also are there any plans on updating the codebase to work around using the old mamba block?

**Comment by yair-schiff** [comment]
@davidaknowles and @gauthamp123, I just pushed a fix to this repo and the HF models that should enable compatibility with the mambav2 repo file structure. Note that the underlying model is still using the original MambaV1 layer, the code will now just no longer throw `ImportError`'s (hopefully).

Please give it a try and let me know if you encounter any new issues. Please free to re-open this issue if you do.

**Comment by davidaknowles** [comment]
That fixed it for me (at least via HF), thank you!
