### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by HUST-Keep-Lin** [kuleshov-group/caduceus#53]
According to your environment configuration, the following error will occur. The reason found online is that the versions of Torch CUDA and Mamba do not match.  ImportError: /home/lkp/anaconda3/envs/caduceus_env/lib/python3.8/site-packages/selective_scan_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorEN3c108optionalINS5_10ScalarTypeEEENS6_INS5_6LayoutEEENS6_INS5_6DeviceEEENS6_IbEENS6_INS5_12MemoryFormatEEE

**Comment by HUST-Keep-Lin** [comment]
How to resolve this issue

**Comment by yair-schiff** [comment]
What versions of mamba-ssm and causal-conv1d do you have installed?

**Comment by HUST-Keep-Lin** [comment]
> m

mamba-ssm==1.2.0.post1  causal-conv1d==1.2.0.post2

**Comment by yair-schiff** [comment]
Ya that should be good. What machine/GPU are you using?

**Comment by HUST-Keep-Lin** [comment]
A40

**Comment by HUST-Keep-Lin** [comment]
> Ya that should be good. What machine/GPU are you using?

A40

**Comment by HUST-Keep-Lin** [comment]
I resolve it.
https://github.com/state-spaces/mamba/releases
