### ISSUE TITLE
How much resources spent on pre-training？

### ISSUE THREAD

**Issue by Jimmy0743** [kuleshov-group/caduceus#55]
Very excellent work！
Just want to know how many GPU and how long had you spent on the pre-training of CADUCEUS-PH and CADUCEUS-PS ?

**Comment by yair-schiff** [comment]
The largest model we trained had 7.7M params and trained on sequences of 131k base pairs. This took about 15 hours (a bit longer for PS and a bit less for Ph) on 8 A100 80 GB GPUs. Please let me know if that helps

**Comment by Jimmy0743** [comment]
That's really helpful! Thanks!
