### ISSUE TITLE
Cannot create environments

### ISSUE THREAD

**Issue by HelloWorldLTY** [kuleshov-group/caduceus#59]
Hi, thanks for your great work. When I try to create the environment based on the yml file, I face an error:

 python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-haadu2xk/flash-attn_edc701d70c664211a57fae455dc49914/setup.py", line 19, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

Would you please help me? Thanks.

**Comment by yair-schiff** [comment]
Can you try creating the env again from scratch, but remove the `flash-attn` dependency from the `yaml`. After the environment is ready, activate it and `pip install` flash-attn separately. Let me know if that helps

**Comment by HelloWorldLTY** [comment]
Yeah I found that work. Would you please change the instructions in the readme file to make it more straightforward? Thanks a lot.

**Comment by yair-schiff** [comment]
I am not sure why the original yaml didn't work for you. I don't think its a consistent issue that others hit. In any case, glad the issue is resolved.
